"use client";
import { useEffect, useState } from "react";
import { Check, ChevronRight, Copy, Sparkles, X } from "lucide-react";
import { AnimatePresence, motion } from "framer-motion";
import { makeCode } from "@/lib/utils";

export function CreateLeagueModal({ open, onClose, onCreated }: { open: boolean; onClose: () => void; onCreated: (name: string, code: string) => void }) {
  const [name, setName] = useState(""); const [step, setStep] = useState<1 | 2>(1); const [code, setCode] = useState(""); const [copied, setCopied] = useState(false);
  useEffect(() => { if (!open) { setTimeout(() => { setStep(1); setName(""); setCopied(false); }, 250); } }, [open]);
  const invite = typeof window === "undefined" ? "" : `${window.location.origin}/join/${code}`;
  const create = () => { if (!name.trim()) return; const c = makeCode(name); setCode(c); setStep(2); onCreated(name.trim(), c); };
  const copy = async () => { await navigator.clipboard.writeText(invite); setCopied(true); setTimeout(() => setCopied(false), 1800); };
  return <AnimatePresence>{open && <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-50 grid place-items-end bg-ink/60 p-0 backdrop-blur-sm sm:place-items-center sm:p-5" onMouseDown={e => e.target === e.currentTarget && onClose()}><motion.div initial={{ y: 40, opacity: 0, scale: .98 }} animate={{ y: 0, opacity: 1, scale: 1 }} exit={{ y: 30, opacity: 0 }} className="w-full overflow-hidden rounded-t-[28px] bg-cream shadow-2xl sm:max-w-lg sm:rounded-[28px]">
    <div className="flex items-center justify-between border-b border-ink/10 px-6 py-5"><span className="text-xs font-extrabold uppercase tracking-[.18em] text-ink/45">{step === 1 ? "New league" : "League ready"}</span><button onClick={onClose} className="grid h-9 w-9 place-items-center rounded-full bg-ink/5 transition hover:bg-ink/10" aria-label="Close"><X size={17}/></button></div>
    {step === 1 ? <div className="p-6 sm:p-8"><div className="mb-6 grid h-14 w-14 place-items-center rounded-2xl bg-lime"><Sparkles size={23}/></div><h2 className="font-display text-3xl font-bold tracking-[-.05em]">Name your league.</h2><p className="mt-2 max-w-sm text-sm leading-6 text-ink/55">Something your group will recognise. You can change it later.</p><label className="mt-7 block text-[11px] font-extrabold uppercase tracking-[.14em] text-ink/50">League name</label><input autoFocus value={name} onChange={e => setName(e.target.value)} onKeyDown={e => e.key === "Enter" && create()} placeholder="e.g. The Sunday XI" maxLength={32} className="mt-2 w-full rounded-2xl border border-ink/15 bg-white px-4 py-4 text-base font-bold outline-none transition focus:border-forest focus:ring-4 focus:ring-forest/10"/><button onClick={create} disabled={!name.trim()} className="mt-5 flex w-full items-center justify-center gap-2 rounded-2xl bg-forest px-5 py-4 text-sm font-extrabold text-white transition hover:bg-ink disabled:opacity-35">Create private league <ChevronRight size={17}/></button></div>
    : <div className="p-6 sm:p-8"><div className="mb-6 grid h-14 w-14 place-items-center rounded-full bg-lime"><Check size={25} strokeWidth={3}/></div><h2 className="font-display text-3xl font-bold tracking-[-.05em]">Bring your people in.</h2><p className="mt-2 text-sm leading-6 text-ink/55">Share this private link. Anyone with it can join <b className="text-ink">{name}</b>.</p><div className="mt-7 rounded-2xl border border-ink/10 bg-white p-2 pl-4"><p className="mb-2 mt-1 text-[10px] font-extrabold uppercase tracking-[.14em] text-ink/40">Invite link · {code}</p><div className="flex items-center gap-2"><p className="min-w-0 flex-1 truncate text-sm font-bold">{invite}</p><button onClick={copy} className="flex shrink-0 items-center gap-2 rounded-xl bg-ink px-4 py-3 text-xs font-extrabold text-white">{copied ? <Check size={15}/> : <Copy size={15}/>} {copied ? "Copied" : "Copy"}</button></div></div><button onClick={onClose} className="mt-5 w-full rounded-2xl bg-lime px-5 py-4 text-sm font-extrabold text-forest">Go to my league</button></div>}
  </motion.div></motion.div>}</AnimatePresence>;
}
